# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on: [push, pull_request]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
  upload-to-bucket:
    runs-on: ubuntu-latest
    needs: [build]
    env:
      BUCKET_NAME: "huynhlkevin.com"
      AWS_REGION: "us-west-1"
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::864899855377:role/S3BucketAccess
          aws-region: ${{ env.AWS_REGION }}
      - name: Upload Files
        run: aws s3 cp ./index.html s3://${{ env.BUCKET_NAME }}