name: Deploy Website Content

on:
  workflow_call:
    inputs:
      rest_api_endpoint:
        required: false
        type: string
      rest_api_key:
        required: false
        type: string
      bucket_name:
        required: false
        type: string
      frontend_automation_aws_role:
        required: false
        type: string
      production:
        required: true
        type: boolean

jobs:
  deploy_website_content:
    runs-on: ubuntu-latest
    environment: ${{ inputs.production && 'production' || 'development' }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: huynhlkevin/personal-website

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'npm'

    - name: Install Node dependencies
      run: npm ci

    - name: Build website content
      run: npm run build
      env:
        REST_API_ENDPOINT: ${{ secrets.REST_API_ENDPOINT || inputs.rest_api_endpoint }}
        REST_API_KEY: ${{ secrets.REST_API_KEY || inputs.rest_api_key }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.FRONTEND_AUTOMATION_AWS_ROLE || inputs.frontend_automation_aws_role }}
        aws-region: "us-west-1"
  
    - name: Sync Files
      run: aws s3 sync ./dist s3://${{ env.BUCKET_NAME }} --delete
      env:
        BUCKET_NAME: ${{ secrets.BUCKET_NAME || inputs.bucket_name }}
