name: Deploy

on:
  workflow_call:
    inputs:
      rest_api_endpoint:
        required: true
        type: string
      rest_api_key:
        required: true
        type: string
      bucket_name:
        required: true
        type: string
  push:
    branches: [ "master" ]

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: "us-west-1"
  AWS_ROLE: ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' && secrets.PRODUCTION_AWS_ROLE || secrets.DEVELOPMENT_AWS_ROLE }}
  REST_API_ENDPOINT: ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' && secrets.PRODUCTION_REST_API_ENDPOINT || inputs.rest_api_endpoint }}
  REST_API_KEY: ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' && secrets.PRODUCTION_REST_API_KEY || inputs.rest_api_key }}
  BUCKET_NAME: ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' && secrets.PRODUCTION_BUCKET_NAME || inputs.bucket_name }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: huynhlkevin/personal-website
        ref: 'refs/heads/create-developer-configuration'
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ env.AWS_ROLE }}
        aws-region: ${{ env.AWS_REGION }}
    - name: Sync Files
      run: aws s3 sync ./dist s3://${{ env.BUCKET_NAME }} --delete
