name: Deploy

on:
  push:
    branches: [ "master" ]

permissions:
  id-token: write
  contents: read

env:
  BUCKET_NAME: "huynhlkevin.com"
  AWS_REGION: "us-west-1"
  REST_API_ENDPOINT: ${{ vars.REST_API_ENDPOINT }}
  REST_API_KEY: ${{ vars.REST_API_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE }}
        aws-region: ${{ env.AWS_REGION }}
    - name: Sync Files
      run: aws s3 sync ./dist s3://${{ env.BUCKET_NAME }} --delete
