name: Deploy Website Content

on:
  workflow_call:
    inputs:
      rest_api_endpoint:
        required: true
        type: string
      rest_api_key:
        required: true
        type: string
      bucket_name:
        required: true
        type: string

jobs:
  deploy_website_content:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: huynhlkevin/personal-website

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'npm'

    - run: npm ci

    - run: npm run build
      env:
        REST_API_ENDPOINT: ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' && secrets.PRODUCTION_REST_API_ENDPOINT || inputs.rest_api_endpoint }}
        REST_API_KEY: ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' && secrets.PRODUCTION_REST_API_KEY || inputs.rest_api_key }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      env:
        AWS_REGION: "us-west-1"
        AWS_ROLE: ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' && secrets.PRODUCTION_AWS_ROLE || secrets.DEVELOPMENT_AWS_ROLE }}
      with:
        role-to-assume: ${{ env.AWS_ROLE }}
        aws-region: ${{ env.AWS_REGION }}
  
    - name: Sync Files
      run: aws s3 sync ./dist s3://${{ env.BUCKET_NAME }} --delete
      env:
        BUCKET_NAME: ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' && secrets.PRODUCTION_BUCKET_NAME || inputs.bucket_name }}
