name: Production

on:
  push:
    branches:
      - master

jobs:
  destroy_development_infrastructure:
    uses: huynhlkevin/personal-website-infrastructure/.github/workflows/destroy_development_infrastructure.yml@main
    secrets: inherit

  deploy_website_content:
    uses: ./.github/workflows/deploy-website-content.yml
    secrets: inherit
    permissions:
      id-token: write
    with:
      production: true