name: Production

on:
  push:
    branches: [master]

jobs:
  deploy_website_content:
    uses: ./.github/workflows/deploy-website-content.yml
    secrets: inherit
    permissions:
      id-token: write
    with:
      production: true

  run_tests_on_website:
    uses: ./.github/workflows/run-tests-on-website.yml
    needs: [deploy_website_content]
    with:
      website_url: www.huynhlkevin.com    