name: Production

on:
  push:
    branches:
      - master

jobs:
  deploy_production_infrastructure:
    uses: huynhlkevin/personal-website-infrastructure/.github/workflows/deploy-production-infrastructure.yml@main
    secrets: inherit

  deploy_website_content:
    uses: ./.github/workflows/deploy-website-content.yaml
    needs: [deploy_production_infrastructure]
    secrets: inherit
    permissions:
      id-token: write
    with:
      production: true

  run_tests_on_website:
    uses: ./.github/workflows/run-tests-on-website.yml
    needs: [deploy_production_infrastructure, deploy_website_content]
    with:
      website_url: www.huynhlkevin.com    