name: Production

on:
  push:
    branches: [main]

jobs:
  deploy_website_content:
    uses: ./.github/workflows/deploy-website-content.yml
    secrets: inherit
    permissions:
      id-token: write
    with:
      production: true