name: Production

on:
  push:
    branches:
      - master

jobs:
  deploy-production-infrastructure:
    uses: huynhlkevin/personal-website-infrastructure/.github/workflows/deploy-production-infrastructure.yaml@main
    secrets: inherit

  deploy-website-content:
    uses: ./.github/workflows/deploy-website-content.yaml
    needs: [deploy-production-infrastructure]
    secrets: inherit
    permissions:
      id-token: write
    with:
      production: true

  run-tests-on-website:
    uses: ./.github/workflows/run-tests-on-website.yaml
    needs: [deploy-production-infrastructure, deploy-website-content]
    with:
      website-url: www.huynhlkevin.com